server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.43.33:3306/accounting
    username: root
    password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
  type-aliases-package: com.myboot.pojo  #对应实体类entity层路径
logging.level.com.myboot.mapper: debug #mybatis配置日志文件，选择自己的mapper层路径




